import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CalendarDays,MapPin,ArrowLeft,ArrowRight } from "lucide-react";
import { getActivity,localized } from "@/lib/activities";
import { Link } from "@/lib/navigation";

export async function generateMetadata({params}:{params:Promise<{locale:string;id:string}>}):Promise<Metadata>{const{locale,id}=await params;const activity=await getActivity(id);if(!activity)return{};const text=localized(activity,locale);return{title:text.title,description:text.description||undefined,openGraph:{title:text.title,description:text.description||undefined,type:"article",images:activity.coverImage?[activity.coverImage]:undefined}}}

export default async function EventDetailPage({params}:{params:Promise<{locale:string;id:string}>}){
 const{locale,id}=await params;const activity=await getActivity(id);if(!activity)notFound();const text=localized(activity,locale);const Arrow=locale==="ar"?ArrowRight:ArrowLeft;const gallery=[...new Set([activity.coverImage,...activity.galleryImages].filter((value):value is string=>Boolean(value)))];
 return <article className="min-h-[70vh] bg-[#f7f8f4]" dir={locale==="ar"?"rtl":"ltr"}><header className="bg-[#0b1f33] py-16 text-white"><div className="container-content max-w-4xl"><Link href="/events" className="inline-flex items-center gap-2 text-sm text-white/70 hover:text-white"><Arrow className="h-4 w-4"/>{locale==="ar"?"العودة إلى الأنشطة":locale==="fr"?"Retour aux activités":"Back to activities"}</Link><h1 className="mt-8 text-3xl font-bold leading-tight md:text-5xl">{text.title}</h1><div className="mt-7 flex flex-wrap gap-5 text-sm text-white/75"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#c8a24a]"/>{activity.date.toLocaleDateString(locale,{year:"numeric",month:"long",day:"numeric"})}</span>{text.location&&<span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[#c8a24a]"/>{text.location}</span>}</div></div></header><div className="container-content max-w-5xl py-12">{gallery.length>0&&<div className="grid gap-4 sm:grid-cols-2">{gallery.map((image,index)=><div key={image} className={`${index===0?"sm:col-span-2 aspect-[16/8]":"aspect-[4/3]"} overflow-hidden rounded-2xl bg-slate-200 shadow-sm`}><div className="h-full w-full bg-cover bg-center" role="img" aria-label={`${text.title} ${index+1}`} style={{backgroundImage:`url(${JSON.stringify(image).slice(1,-1)})`}}/></div>)}</div>}<div className="mx-auto max-w-3xl py-10"><p className="text-lg leading-9 text-[#374151]">{text.description}</p><div className="mt-12 rounded-xl border-s-4 border-[#c8a24a] bg-white p-6"><p className="font-semibold text-[#0b1f33]">{locale==="ar"?"يأتي هذا النشاط ضمن عمل المركز في دعم الحوار الاقتصادي والتعاون المؤسساتي والتنمية الوطنية.":locale==="fr"?"Cette activité s’inscrit dans l’action du centre en faveur du dialogue économique, de la coopération institutionnelle et du développement national.":"This activity forms part of the center’s work to advance economic dialogue, institutional cooperation, and national development."}</p></div></div></div></article>;
}
