"use client";
import { useRef,useState } from "react";
import { CheckCircle2,ImagePlus,Sparkles } from "lucide-react";
export function ImageUploadField({name,label,currentImage,maxMb=8,preserveName}:{name:string;label:string;currentImage?:string|null;maxMb?:number;preserveName?:string}){
 const ref=useRef<HTMLInputElement>(null);const[fileName,setFileName]=useState("");const[preview,setPreview]=useState(currentImage||"");
 function select(file?:File){if(!file)return;setFileName(file.name);setPreview(URL.createObjectURL(file));}
 function drop(file?:File){if(!file||!ref.current)return;const transfer=new DataTransfer();transfer.items.add(file);ref.current.files=transfer.files;select(file);}
 return <div><input ref={ref} name={name} type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="sr-only" onChange={e=>select(e.target.files?.[0])}/>{currentImage&&<input type="hidden" name={preserveName||name.replace(/File$/,"")} value={currentImage}/>}<button type="button" onClick={()=>ref.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop(e.dataTransfer.files[0]);}} className="group relative w-full overflow-hidden rounded-2xl border-2 border-dashed border-primary/30 bg-primary/[0.03] p-6 text-center transition duration-300 hover:-translate-y-0.5 hover:border-primary hover:bg-primary/[0.07] hover:shadow-[0_0_28px_rgba(11,122,83,.18)] focus:outline-none focus:ring-4 focus:ring-primary/15"><span className="pointer-events-none absolute -left-16 top-0 h-full w-12 rotate-12 bg-white/70 blur-md transition-all duration-700 group-hover:left-[110%]"/><span className="relative flex flex-col items-center">{preview?<span className="mb-3 h-24 w-24 overflow-hidden rounded-xl border bg-white shadow-sm"><span className="block h-full w-full bg-cover bg-center" style={{backgroundImage:`url(${JSON.stringify(preview).slice(1,-1)})`}}/></span>:<span className="mb-3 rounded-full bg-primary/10 p-3 text-primary transition group-hover:scale-110"><ImagePlus className="h-7 w-7"/></span>}<span className="flex items-center gap-2 font-bold text-slate-900">{label}<Sparkles className="h-4 w-4 text-[#c8a24a] opacity-0 transition group-hover:opacity-100"/></span><span className="mt-2 text-xs text-slate-500">Click or drag an image here · JPG, PNG, WebP, GIF · Max {maxMb} MB</span>{fileName&&<span className="mt-3 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"><CheckCircle2 className="h-4 w-4"/>{fileName}</span>}</span></button></div>;
}
