import { Trash2 } from "lucide-react";
import type { LeadershipMember } from "@/lib/structure";
import { removeLeadershipMember, saveLeadershipMember } from "@/app/[locale]/admin/actions";
import { ImageUploadField } from "./ImageUploadField";

const input="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-primary";
const languages=[{code:"Ar",label:"العربية",dir:"rtl"},{code:"Fr",label:"Français",dir:"ltr"},{code:"En",label:"English",dir:"ltr"}] as const;

export function LeadershipEditor({locale,members}:{locale:string;members:LeadershipMember[]}){
 const t=locale==="ar"?{title:"أعضاء الفريق",help:"تعديل أسماء الأعضاء ومناصبهم وصورهم.",upload:"اختيار صورة جديدة",name:"الاسم",role:"المنصب",save:"حفظ التغييرات",remove:"حذف العضو",protected:"لا يمكن حذف الرئيس"}:locale==="fr"?{title:"Membres de l’équipe",help:"Modifiez les noms, fonctions et photos.",upload:"Choisir une nouvelle photo",name:"Nom",role:"Fonction",save:"Enregistrer",remove:"Supprimer",protected:"Le président ne peut pas être supprimé"}:{title:"Team members",help:"Edit names, roles, and photos.",upload:"Choose a new photo",name:"Name",role:"Role",save:"Save changes",remove:"Remove member",protected:"The president cannot be removed"};
 return <section className="mt-10"><div className="mb-6"><h2 className="text-2xl font-bold">{t.title}</h2><p className="mt-2 text-sm text-slate-500">{t.help}</p></div><div className="space-y-6">{members.map(member=><article key={member.id} className="rounded-2xl border bg-white p-6 shadow-sm"><form action={saveLeadershipMember.bind(null,locale,member.id)}><div className="mb-5 flex items-center gap-3"><span className={`flex h-12 w-12 items-center justify-center rounded-full bg-gradient-to-br font-bold text-white ${member.accent}`}>{member.initials}</span><div><h3 className="font-bold">{member.name[locale as "ar"|"fr"|"en"]}</h3><p className="text-sm text-slate-500">{member.role[locale as "ar"|"fr"|"en"]}</p></div></div><div className="grid gap-5 lg:grid-cols-[1fr_1.25fr]"><ImageUploadField name="imageFile" preserveName="imageUrl" label={t.upload} currentImage={member.imageUrl}/><div className="grid gap-4 sm:grid-cols-2">{languages.map(l=><fieldset key={l.code} dir={l.dir} className="rounded-xl border p-4 sm:col-span-2 lg:col-span-1"><legend className="px-2 text-sm font-bold">{l.label}</legend><label className="block text-xs font-semibold">{t.name}<input name={`name${l.code}`} required defaultValue={member.name[l.code.toLowerCase() as "ar"|"fr"|"en"]} className={input}/></label><label className="mt-3 block text-xs font-semibold">{t.role}<input name={`role${l.code}`} required defaultValue={member.role[l.code.toLowerCase() as "ar"|"fr"|"en"]} className={input}/></label></fieldset>)}</div></div><div className="mt-5 flex justify-end"><button className="rounded-lg bg-primary px-5 py-2.5 text-sm font-bold text-white">{t.save}</button></div></form><div className="mt-4 border-t pt-4">{member.id==="president"?<p className="text-xs text-slate-400">{t.protected}</p>:<form action={removeLeadershipMember.bind(null,locale,member.id)}><button className="inline-flex items-center gap-2 text-sm font-semibold text-red-700"><Trash2 className="h-4 w-4"/>{t.remove}</button></form>}</div></article>)}</div></section>;
}
