"use client";
import { useMemo,useRef,useState } from "react";
import { CheckCircle2,Images,Plus,Sparkles,Star } from "lucide-react";

export function MultiImageUploadField({existingImages=[],mainImage,label}:{existingImages?:string[];mainImage?:string|null;label:string}){
 const ref=useRef<HTMLInputElement>(null);const[files,setFiles]=useState<File[]>([]);const[main,setMain]=useState(mainImage?`existing:${mainImage}`:existingImages[0]?`existing:${existingImages[0]}`:"");
 const previews=useMemo(()=>files.map(file=>({file,url:URL.createObjectURL(file)})),[files]);
 function add(incoming:FileList|File[]){const valid=Array.from(incoming).filter(file=>file.type.startsWith("image/"));setFiles(current=>{const next=[...current,...valid];if(!main&&next.length)setMain("new:0");return next;});}
 return <div><input ref={ref} name="galleryFiles" type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" data-max-mb="8" className="sr-only" onChange={event=>event.target.files&&add(event.target.files)}/><input type="hidden" name="existingGalleryImages" value={JSON.stringify(existingImages)}/><input type="hidden" name="mainImageChoice" value={main}/><button type="button" onClick={()=>ref.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();add(e.dataTransfer.files);}} className="group relative w-full overflow-hidden rounded-2xl border-2 border-dashed border-primary/35 bg-primary/[0.04] p-7 text-center transition hover:-translate-y-0.5 hover:border-primary hover:bg-primary/[0.08] focus:ring-4 focus:ring-primary/15"><span className="pointer-events-none absolute -left-16 top-0 h-full w-12 rotate-12 bg-white/80 blur-md transition-all duration-700 group-hover:left-[110%]"/><span className="relative flex flex-col items-center"><span className="rounded-full bg-primary/10 p-3 text-primary transition group-hover:scale-110"><Images className="h-8 w-8"/></span><strong className="mt-3 flex items-center gap-2">{label}<Sparkles className="h-4 w-4 text-[#c8a24a]"/></strong><span className="mt-2 text-xs text-slate-500">Click or drag several images here · Maximum 8 MB each</span><span className="mt-3 inline-flex items-center gap-2 rounded-full bg-primary px-3 py-1.5 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Add pictures</span></span></button>{(existingImages.length>0||previews.length>0)&&<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{existingImages.map((url,index)=><Picture key={`existing-${index}`} url={url} value={`existing:${url}`} checked={main===`existing:${url}`} onSelect={setMain}/>) }{previews.map(({file,url},index)=><Picture key={`${file.name}-${index}`} url={url} name={file.name} value={`new:${index}`} checked={main===`new:${index}`} onSelect={setMain}/>)}</div>}</div>;
}

function Picture({url,name,value,checked,onSelect}:{url:string;name?:string;value:string;checked:boolean;onSelect:(value:string)=>void}){return <button type="button" onClick={()=>onSelect(value)} className={`group relative overflow-hidden rounded-xl border-2 bg-white p-2 text-start transition hover:-translate-y-1 hover:shadow-lg ${checked?"border-[#c8a24a] ring-4 ring-[#c8a24a]/20":"border-slate-200 hover:border-primary/50"}`}><span className="block aspect-video rounded-lg bg-cover bg-center" style={{backgroundImage:`url(${JSON.stringify(url).slice(1,-1)})`}}/><span className="mt-2 flex items-center justify-between gap-2 text-xs"><span className="truncate text-slate-500">{name||"Saved image"}</span>{checked?<span className="inline-flex items-center gap-1 font-bold text-[#9a741e]"><Star className="h-4 w-4 fill-current"/>Main</span>:<span className="font-semibold text-primary opacity-0 transition group-hover:opacity-100">Set as main</span>}</span>{checked&&<CheckCircle2 className="absolute end-3 top-3 h-6 w-6 rounded-full bg-white text-[#c8a24a]"/>}</button>}
