import { CalendarDays, FileText, Handshake, ImagePlus, Languages, Settings2 } from "lucide-react";
import { saveEvent, savePartner, savePublication, saveSiteSettings, updateEvent } from "@/app/[locale]/admin/actions";
import type { Event, PublicationCategory } from "@prisma/client";
import { FriendlySlugField } from "./FriendlySlugField";
import { ImageUploadField } from "./ImageUploadField";
import { MultiImageUploadField } from "./MultiImageUploadField";
import { AdminForm } from "./AdminForm";

const input = "mt-2 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10";
const area = "mt-2 w-full rounded-lg border border-slate-200 bg-white p-3 text-sm leading-6 outline-none focus:border-primary focus:ring-2 focus:ring-primary/10";
const section = "rounded-2xl border border-slate-200 bg-white p-6 shadow-sm";
const languages = [
  { code: "Ar", label: "Arabic · العربية", dir: "rtl" as const },
  { code: "Fr", label: "French · Français", dir: "ltr" as const },
  { code: "En", label: "English", dir: "ltr" as const },
];

function Heading({ icon: Icon, title, help }: { icon: typeof Languages; title: string; help: string }) {
  return <div className="mb-5 flex gap-3"><span className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{help}</p></div></div>;
}

function SlugField() {
  return <FriendlySlugField />;
}

function ImageFields({ prefix = "coverImage", label = "Cover image", currentImage }: { prefix?: "coverImage" | "logo"; label?: string; currentImage?:string|null }) {
  return <section className={section}><Heading icon={ImagePlus} title={label} help="Click the area below or drag an image into it."/><ImageUploadField name={`${prefix}File`} label="Choose image" currentImage={currentImage}/></section>;
}

function PublishBar({ noun, published=false }: { noun: string; published?:boolean }) {
  return <section className={`${section} flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between`}><label className="flex cursor-pointer items-start gap-3"><input name="published" type="checkbox" defaultChecked={published} className="mt-1 h-4 w-4 accent-primary"/><span><strong className="block text-sm">Publish immediately</strong><span className="text-xs text-slate-500">Leave unchecked to save as a draft.</span></span></label><button className="rounded-lg bg-primary px-6 py-3 text-sm font-bold text-white">Save {noun}</button></section>;
}

export function EventForm({ locale, initial }: { locale: string; initial?:Event|null }) {
  const dateInput=(value?:Date|null)=>value?new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16):"";
  return <AdminForm action={initial?updateEvent.bind(null,locale,initial.id):saveEvent.bind(null, locale)} locale={locale} successRedirect={`/${locale}/admin/events`} className="space-y-6">
    <section className={section}><Heading icon={CalendarDays} title="Event details" help="Set the event address, type, schedule, and optional registration link."/><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><SlugField/></div><label className="text-sm font-semibold">Event type <span className="text-red-600">*</span><select name="category" required defaultValue={initial?.category||"ORGANIZED"} className={input}><option value="ORGANIZED">Organized by ACEFIDE</option><option value="PARTICIPATION">ACEFIDE participation</option><option value="MEETING">Meeting</option><option value="MEDIA">Media appearance</option></select></label><label className="text-sm font-semibold">Speakers or guests<input name="speakers" defaultValue={initial?.speakers||""} placeholder="Names separated by commas" className={input}/></label><label className="text-sm font-semibold">Start date and time <span className="text-red-600">*</span><input name="date" type="datetime-local" required defaultValue={dateInput(initial?.date)} className={input}/></label><label className="text-sm font-semibold">End date and time <span className="font-normal text-slate-500">(optional)</span><input name="endDate" type="datetime-local" defaultValue={dateInput(initial?.endDate)} className={input}/></label><label className="text-sm font-semibold md:col-span-2">Registration link <span className="font-normal text-slate-500">(optional)</span><input name="registrationLink" type="url" defaultValue={initial?.registrationLink||""} placeholder="https://..." className={input}/></label></div></section>
    <section className={section}><Heading icon={Languages} title="Event information in three languages" help="Titles are required. Descriptions and locations help visitors understand the event."/><div className="space-y-6">{languages.map(l=><fieldset key={l.code} dir={l.dir} className="rounded-xl border bg-slate-50/60 p-5"><legend className="px-2 text-sm font-bold text-primary">{l.label}</legend><div className="space-y-4"><label className="block text-sm font-semibold">Event title <span className="text-red-600">*</span><input name={`title${l.code}`} required defaultValue={initial?.[`title${l.code}` as "titleAr"|"titleFr"|"titleEn"]||""} placeholder="Enter the event title" className={input}/></label><label className="block text-sm font-semibold">Description<textarea name={`description${l.code}`} rows={4} defaultValue={initial?.[`description${l.code}` as "descriptionAr"|"descriptionFr"|"descriptionEn"]||""} placeholder="What is this event about?" className={area}/></label><label className="block text-sm font-semibold">Location<input name={`location${l.code}`} defaultValue={initial?.[`location${l.code}` as "locationAr"|"locationFr"|"locationEn"]||""} placeholder="Venue, city, or online" className={input}/></label></div></fieldset>)}</div></section>
    <section className={section}><Heading icon={ImagePlus} title="Event pictures" help="Add several images and click one to use it as the main cover."/><MultiImageUploadField label="Add event pictures" existingImages={initial?[...new Set([initial.coverImage,...initial.galleryImages].filter((value):value is string=>Boolean(value)))]:[]} mainImage={initial?.coverImage}/></section><PublishBar noun="event" published={initial?.published}/>
  </AdminForm>;
}

export function PublicationForm({ locale, fixedCategory = null }: { locale: string; fixedCategory?: PublicationCategory | null }) {
  const noun = fixedCategory === "STUDY" ? "study" : "publication";
  return <AdminForm action={savePublication.bind(null, locale, fixedCategory)} locale={locale} successRedirect={`/${locale}/admin/${fixedCategory === "STUDY" ? "studies" : "publications"}`} className="space-y-6">
    <section className={section}><Heading icon={FileText} title={`${noun[0].toUpperCase()+noun.slice(1)} details`} help="Give the document a unique web address and choose how it should be classified."/><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><SlugField/></div>{!fixedCategory&&<label className="text-sm font-semibold">Publication type <span className="text-red-600">*</span><select name="category" required className={input}><option value="REPORT">Report</option><option value="ANALYSIS">Analysis</option><option value="POLICY_BRIEF">Policy brief</option><option value="STUDY">Study</option></select></label>}</div></section>
    <section className={section}><Heading icon={Languages} title="Titles and summaries" help="Add a reader-friendly title and summary in all three languages."/><div className="space-y-6">{languages.map(l=><fieldset key={l.code} dir={l.dir} className="rounded-xl border bg-slate-50/60 p-5"><legend className="px-2 text-sm font-bold text-primary">{l.label}</legend><label className="block text-sm font-semibold">Title <span className="text-red-600">*</span><input name={`title${l.code}`} required className={input}/></label><label className="mt-4 block text-sm font-semibold">Summary <span className="text-red-600">*</span><textarea name={`summary${l.code}`} required rows={5} placeholder="Explain what readers will learn from this document" className={area}/></label></fieldset>)}</div></section>
    <ImageFields/>
    <section className={section}><Heading icon={FileText} title="Downloadable document" help="Upload the document visitors will download, or link to one already hosted online."/><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Upload PDF/document<input name="pdfFile" type="file" accept="application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text" className="mt-2 block w-full rounded-lg border p-2 text-sm font-normal"/><span className="mt-2 block text-xs font-normal text-slate-500">PDF, DOC, DOCX, ODT · Maximum 25 MB</span></label><label className="text-sm font-semibold">Or paste a document URL<input name="pdfUrl" type="url" placeholder="https://example.com/document.pdf" className={input}/></label></div></section>
    <PublishBar noun={noun}/>
  </AdminForm>;
}

export function PartnerForm({ locale }: { locale: string }) {
  return <AdminForm action={savePartner.bind(null, locale)} locale={locale} successRedirect={`/${locale}/admin/partners`} className="space-y-6">
    <section className={section}><Heading icon={Handshake} title="Partner details" help="Identify the organization, its type, website, and display order."/><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><SlugField/></div><label className="text-sm font-semibold">Partner type<select name="category" className={input}><option value="INSTITUTIONAL">Institutional</option><option value="GOVERNMENT">Government</option><option value="INTERNATIONAL">International</option><option value="UNIVERSITY">University</option><option value="PRIVATE">Private sector</option></select></label><label className="text-sm font-semibold">Display order<input name="order" type="number" min="0" defaultValue="0" className={input}/><span className="mt-2 block text-xs font-normal text-slate-500">Lower numbers appear first.</span></label><label className="text-sm font-semibold md:col-span-2">Website<input name="website" type="url" placeholder="https://partner.example" className={input}/></label></div></section>
    <section className={section}><Heading icon={Languages} title="Names and collaboration details" help="Explain what this collaboration aims to achieve in Arabic, French, and English."/><div className="space-y-6">{languages.map(l=><fieldset key={l.code} dir={l.dir} className="rounded-xl border bg-slate-50/60 p-5"><legend className="px-2 text-sm font-bold text-primary">{l.label}</legend><label className="block text-sm font-semibold">Organization name <span className="text-red-600">*</span><input name={`name${l.code}`} required className={input}/></label><label className="mt-4 block text-sm font-semibold">Collaboration aims and details<textarea name={`description${l.code}`} rows={6} placeholder="Describe the partnership objectives, activities, and expected impact" className={area}/></label></fieldset>)}</div></section>
    <ImageFields prefix="logo" label="Partner logo"/><PublishBar noun="partner"/>
  </AdminForm>;
}

export function SiteSettingsForm({ locale, values }: { locale: string; values: Record<string,string> }) {
  return <AdminForm action={saveSiteSettings.bind(null, locale)} locale={locale} className="space-y-6"><section className={section}><Heading icon={Settings2} title="Organization identity" help="These names and contact details are shared across the public website."/><div className="space-y-5">{languages.map(l=><label key={l.code} dir={l.dir} className="block text-sm font-semibold">Organization name · {l.label}<input name={`site_name_${l.code.toLowerCase()}`} required defaultValue={values[`site_name_${l.code.toLowerCase()}`]} className={input}/></label>)}</div></section><section className={section}><Heading icon={Settings2} title="Contact information" help="Use the public details visitors should use to reach ACEFIDE."/><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Public email<input name="contact_email" type="email" defaultValue={values.contact_email} className={input}/></label><label className="text-sm font-semibold">Public phone<input name="contact_phone" type="tel" defaultValue={values.contact_phone} className={input}/></label>{languages.map(l=><label key={l.code} dir={l.dir} className="text-sm font-semibold md:col-span-2">Address · {l.label}<input name={`contact_address_${l.code.toLowerCase()}`} defaultValue={values[`contact_address_${l.code.toLowerCase()}`]} className={input}/></label>)}</div></section><section className={section}><Heading icon={Settings2} title="Social media and map" help="Leave any service blank if ACEFIDE does not use it."/><div className="grid gap-5 md:grid-cols-2">{[["facebook_url","Facebook URL"],["linkedin_url","LinkedIn URL"],["youtube_url","YouTube URL"],["map_embed_url","Map embed URL"]].map(([name,label])=><label key={name} className="text-sm font-semibold">{label}<input name={name} type="url" defaultValue={values[name]} className={input}/></label>)}</div></section><div className="flex justify-end"><button className="rounded-lg bg-primary px-6 py-3 text-sm font-bold text-white">Save site settings</button></div></AdminForm>;
}
