import { prisma } from "@/lib/prisma";
import { Link } from "@/lib/navigation";
import { BookOpen, ExternalLink, FileCheck2, ShieldCheck } from "lucide-react";

const documentedOutputs = [
  {
    title: { ar: "توصيات ملتقى الإعلام الوطني والرقمي والاستثمار", fr: "Recommandations du forum sur les médias et l’investissement", en: "Recommendations from the media and investment forum" },
    summary: { ar: "توصيات لتعزيز إبراز الإصلاحات الاقتصادية، وتوسيع التشاور مع المتعاملين، وترقية الإعلام الاقتصادي المتخصص والثقافة القانونية والإنتاج السمعي البصري الاقتصادي.", fr: "Recommandations visant à mieux faire connaître les réformes économiques, renforcer la concertation, développer la presse économique spécialisée, la culture juridique et la production audiovisuelle économique.", en: "Recommendations to communicate economic reforms, deepen consultation with operators, develop specialized economic journalism, improve legal awareness, and expand economic audiovisual production." },
    date: "18.02.2024",
    source: "https://algeriainvest.com/en/premium-news/relance-de-linvestissement-limportance-de-mettre-en-valeur-les-reformes-economiques-soulignee-1",
  },
  {
    title: { ar: "توصيات حول تطوير قطاع المناجم", fr: "Recommandations pour le développement du secteur minier", en: "Recommendations for mining-sector development" },
    summary: { ar: "محاور تشمل التحويل المحلي، وجذب الاستثمار الأجنبي، وتحسين البنية التحتية، وإشراك المؤسسات الصغيرة والمتوسطة والجامعة، وإنشاء نظام وطني للمعلومات المنجمية واستراتيجية تصدير مستدامة.", fr: "Axes portant sur la transformation locale, l’investissement étranger, les infrastructures, la mobilisation des PME et des universités, un système national d’information minière et une stratégie d’exportation durable.", en: "Priorities include local transformation, foreign investment, infrastructure, SME and university participation, a national mining-information system, and a sustainable export strategy." },
    date: "02.06.2025",
    source: "https://lechodalgerie.dz/sonarem-sallie-a-des-partenaires-internationaux-pour-dynamiser-lindustrie-miniere-des-projets-structurants-en-preparation-avec-la-chine-le-canada-la-turquie-et-oman/",
  },
] as const;

export default async function Publications({ params }: { params: Promise<{locale:string}> }) {
  const { locale } = await params;
  const lang = locale as "ar" | "fr" | "en";
  const items = await prisma.publication.findMany({ where: { published: true }, orderBy: { publishedAt: "desc" } }).catch(() => []);
  const copy = lang === "ar" ? { title: "الدراسات والمنشورات", outputs: "مخرجات وتوصيات موثقة", note: "لم نعثر في المصادر العامة على دراسة كاملة أو ملف PDF رسمي منشور باسم المركز. لذلك نعرض فقط المخرجات الموثقة ولا ننسب للمركز دراسات غير منشورة." } : lang === "fr" ? { title: "Études et publications", outputs: "Résultats et recommandations documentés", note: "Aucune étude complète ni PDF officiel publié au nom du centre n’a été trouvé dans les sources publiques consultées. Cette page évite donc d’attribuer au centre des études non publiées." } : { title: "Studies and publications", outputs: "Documented outputs and recommendations", note: "No complete study or official PDF published under ACEFIDE’s name was found in the public sources reviewed. This page therefore avoids attributing unpublished studies to the center." };
  return <div dir={lang === "ar" ? "rtl" : "ltr"}><header className="bg-[#0b1f33] py-20 text-white"><div className="container-content"><p className="section-kicker !text-[#e5c978]">ACEFIDE</p><h1 className="mt-4 text-4xl font-bold md:text-5xl">{copy.title}</h1></div></header><section className="bg-[#f3f6f1] py-16"><div className="container-content"><div className="mb-8 flex items-start gap-3 rounded-xl border border-primary/15 bg-white p-5 text-sm leading-6 text-muted-foreground"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p>{copy.note}</p></div>{items.length > 0 && <div className="mb-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((x) => { const title=lang === "ar" ? x.titleAr : lang === "fr" ? x.titleFr : x.titleEn; const summary=lang === "ar" ? x.summaryAr : lang === "fr" ? x.summaryFr : x.summaryEn; return <article key={x.id} className="surface-card p-6"><BookOpen className="text-primary" /><Link href={`/publications/${x.slug}`}><h2 className="mt-5 text-xl font-bold text-[#0b1f33]">{title}</h2></Link><p className="mt-3 text-sm leading-6 text-muted-foreground">{summary}</p></article>; })}</div>}<h2 className="mb-6 text-2xl font-bold text-[#0b1f33]">{copy.outputs}</h2><div className="grid gap-5 md:grid-cols-2">{documentedOutputs.map((item) => <article key={item.title.en} className="surface-card p-7"><FileCheck2 className="h-7 w-7 text-primary" /><p className="mt-5 text-xs font-bold text-accent">{item.date}</p><h3 className="mt-2 text-xl font-bold leading-7 text-[#0b1f33]">{item.title[lang]}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{item.summary[lang]}</p><a href={item.source} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">{lang === "ar" ? "المصدر" : lang === "fr" ? "Source" : "Source"}<ExternalLink className="h-4 w-4" /></a></article>)}</div></div></section></div>;
}
