"use client";
import { useLocale } from "next-intl";
import { Link } from "@/lib/navigation";
import { ArrowLeft, ArrowRight, BarChart3, BriefcaseBusiness, GraduationCap, Handshake, Megaphone, MessagesSquare } from "lucide-react";

const focus = [
  { icon: BarChart3, ar: "الاستشراف الاقتصادي", fr: "Prospective économique", en: "Economic foresight" }, { icon: BriefcaseBusiness, ar: "تطوير الاستثمار", fr: "Développement de l’investissement", en: "Investment development" }, { icon: GraduationCap, ar: "دعم المقاولاتية", fr: "Soutien à l’entrepreneuriat", en: "Entrepreneurship support" }, { icon: MessagesSquare, ar: "الحوار المؤسساتي", fr: "Dialogue institutionnel", en: "Institutional dialogue" }, { icon: Megaphone, ar: "الإعلام والتوعية", fr: "Médias et sensibilisation", en: "Media and public awareness" }, { icon: Handshake, ar: "الشراكات", fr: "Partenariats", en: "Partnerships" },
];
export function AboutFocusSection() {
  const locale = useLocale() as "ar"|"fr"|"en"; const Arrow = locale === "ar" ? ArrowLeft : ArrowRight;
  const copy = { ar: {eyebrow:"مساهمتنا في  تطوير الإقتصاد",title:"منصة وطنية للحوار والعمل الاقتصادي",body:"المركز الجزائري للاستشراف الاقتصادي وتطوير الاستثمار والمقاولاتية جمعية وطنية تُعنى باستشراف التحولات الاقتصادية ودعم الاستثمار وروح المبادرة. يجمع المركز المؤسسات الاقتصادية والجامعات والهيئات العمومية وحاملي المشاريع ضمن فضاء للتعاون وتبادل الخبرات، بهدف بلورة رؤى عملية وتوصيات تسهم في دفع عجلة التنمية الوطنية.",link:"تعرف على المركز",focus:"مجالات عملنا"}, fr:{eyebrow:"Notre rôle économique",title:"Une plateforme nationale de dialogue et d’action économique",body:"ACEFIDE est une association nationale à vocation économique. Le centre établit des passerelles entre institutions économiques, universités, organismes publics et porteurs de projets afin de formuler des perspectives et recommandations au service du développement national.",link:"Découvrir le centre",focus:"Nos domaines d’action"}, en:{eyebrow:"Our economic role",title:"A national platform for economic dialogue and action",body:"ACEFIDE is a national economic association. The center builds cooperation between economic institutions, universities, public bodies, and project owners while developing insights and recommendations that support national development.",link:"About the center",focus:"Our focus areas"} }[locale];
  return <section className="bg-white py-20" dir={locale === "ar" ? "rtl" : "ltr"}><div className="container-content grid gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-primary">{copy.eyebrow}</p><h2 className="mt-4 text-3xl font-bold leading-tight text-[#0b1f33] md:text-4xl">{copy.title}</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">{copy.body}</p><Link href="/about" className="mt-8 inline-flex items-center gap-2 font-bold text-primary">{copy.link}<Arrow className="h-4 w-4"/></Link></div><div><h3 className="mb-5 text-sm font-bold uppercase tracking-widest text-[#c8a24a]">{copy.focus}</h3><div className="grid gap-3 sm:grid-cols-2">{focus.map(({icon:Icon,...item}) => <div key={item.en} className="flex items-center gap-4 rounded-xl border bg-[#f7f8f6] p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-white text-primary shadow-sm"><Icon className="h-5 w-5"/></div><span className="font-semibold text-[#111827]">{item[locale]}</span></div>)}</div></div></div></section>;
}
