CREATE TABLE IF NOT EXISTS "MembershipRequest" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "organization" TEXT,
    "position" TEXT,
    "reason" TEXT,
    "dateOfBirth" TIMESTAMP(3),
    "placeOfBirth" TEXT,
    "nationalId" TEXT,
    "address" TEXT,
    "wilaya" TEXT,
    "educationLevel" TEXT,
    "employmentStatus" TEXT,
    "membershipCategory" TEXT,
    "interests" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "previousAssociation" BOOLEAN,
    "previousAssociationDetails" TEXT,
    "socialLinks" TEXT,
    "identityDocumentUrl" TEXT,
    "personalPhotoUrl" TEXT,
    "cvUrl" TEXT,
    "diplomaUrl" TEXT,
    "criminalRecordUrl" TEXT,
    "duesReceiptUrl" TEXT,
    "declarationAccepted" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MembershipRequest_pkey" PRIMARY KEY ("id")
);
