import { prisma } from "@/lib/prisma";
import { Link } from "@/lib/navigation";
import { CalendarDays, Handshake, Mail, MessageSquare, Newspaper, Users, FileText, Inbox } from "lucide-react";

async function dashboardData() {
  try {
    const [news, events, publications, partners, contacts, members, consultations, subscribers, recentContacts, recentMembers] = await prisma.$transaction([
      prisma.news.count(), prisma.event.count(), prisma.publication.count(), prisma.partner.count(), prisma.contactMessage.count(), prisma.membershipRequest.count(), prisma.consultationRequest.count(), prisma.newsletterSubscriber.count({ where: { active: true } }), prisma.contactMessage.findMany({ take: 5, orderBy: { createdAt: "desc" } }), prisma.membershipRequest.findMany({ take: 5, orderBy: { createdAt: "desc" } }),
    ]); return { counts: { news, events, publications, partners, contacts, members, consultations, subscribers }, recentContacts, recentMembers };
  } catch { return { counts: { news:0, events:0, publications:0, partners:0, contacts:0, members:0, consultations:0, subscribers:0 }, recentContacts: [], recentMembers: [] }; }
}
export default async function AdminDashboard({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const data = await dashboardData(); const cards = [
    ["news", data.counts.news, Newspaper, "/admin/news"], ["events", data.counts.events, CalendarDays, "/admin/events"], ["publications", data.counts.publications, FileText, "/admin/publications"], ["partners", data.counts.partners, Handshake, "/admin/partners"], ["contact messages", data.counts.contacts, Inbox, "/admin/messages"], ["membership requests", data.counts.members, Users, "/admin/members"], ["consultations", data.counts.consultations, MessageSquare, "/admin/consultations"], ["subscribers", data.counts.subscribers, Mail, "/admin/subscribers"],
  ] as const;
  return <div dir={locale === "ar" ? "rtl" : "ltr"}><div className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-primary">ACEFIDE</p><h1 className="mt-2 text-3xl font-bold text-[#0b1f33]">{locale === "ar" ? "لوحة التحكم" : locale === "fr" ? "Tableau de bord" : "Dashboard"}</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,count,Icon,href]) => <Link href={href} key={label} className="rounded-xl border bg-white p-5 shadow-sm transition hover:shadow-md"><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5"/></div><span className="text-3xl font-bold text-[#0b1f33]">{count}</span></div><p className="mt-5 text-sm font-semibold capitalize text-muted-foreground">{label}</p></Link>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-white p-6"><h2 className="font-bold">{locale === "ar" ? "أحدث رسائل الاتصال" : "Recent contact messages"}</h2><div className="mt-4 divide-y">{data.recentContacts.map(item => <div key={item.id} className="py-3"><p className="font-semibold">{item.name}</p><p className="truncate text-sm text-muted-foreground">{item.subject}</p></div>)}{!data.recentContacts.length && <p className="py-8 text-sm text-muted-foreground">No submissions yet.</p>}</div></section><section className="rounded-xl border bg-white p-6"><h2 className="font-bold">{locale === "ar" ? "أحدث طلبات العضوية" : "Recent membership requests"}</h2><div className="mt-4 divide-y">{data.recentMembers.map(item => <div key={item.id} className="py-3"><p className="font-semibold">{item.name}</p><p className="text-sm text-muted-foreground">{item.email}</p></div>)}{!data.recentMembers.length && <p className="py-8 text-sm text-muted-foreground">No submissions yet.</p>}</div></section></div></div>;
}
